name: grinta
description: Grinta Coffee Shop Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  file_picker: ^4.0.1
  fluttericon: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  image_picker: ^0.8.4+1
  firebase_storage: ^10.0.3
  path: ^1.8.0
  cached_network_image: ^3.1.0
  dropdown_search: ^1.0.0
  carousel_slider: ^4.0.0
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
